"""add_market_data_delay_columns_to_pairs

Revision ID: 05a02ce2c7c3
Revises: 883b68f3350b
Create Date: 2025-08-25 13:09:47.735712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a02ce2c7c3'
down_revision: Union[str, None] = '883b68f3350b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairs_table', sa.Column('max_md_delay_1', sa.Integer(), nullable=True))
    op.add_column('pairs_table', sa.Column('max_md_delay_2', sa.Integer(), nullable=True))
    op.add_column('pairs_table', sa.Column('md_delay_flag', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairs_table', 'md_delay_flag')
    op.drop_column('pairs_table', 'max_md_delay_2')
    op.drop_column('pairs_table', 'max_md_delay_1')
    # ### end Alembic commands ###
