"""portfolio_config расширен: strategy_id, mode, qty_ratio, price_ratio, threshold, leaves_qty

Revision ID: 0c2271c73cb4
Revises: d8d5b2c19a7c
Create Date: 2025-05-05 18:12:51.317099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2271c73cb4'
down_revision: Union[str, None] = 'd8d5b2c19a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_configs', sa.Column('strategy_id', sa.Integer(), nullable=True, comment='ID стратегии (тип)'))
    op.add_column('portfolio_configs', sa.Column('mode', sa.String(length=16), nullable=True, comment='Режим работы (shooter, market_maker и др.)'))
    op.add_column('portfolio_configs', sa.Column('qty_ratio', sa.String(length=64), nullable=True, comment='Коэффициенты объёма (формула или число)'))
    op.add_column('portfolio_configs', sa.Column('price_ratio', sa.String(length=64), nullable=True, comment='Коэффициенты цены (формула или число)'))
    op.add_column('portfolio_configs', sa.Column('threshold', sa.Numeric(precision=18, scale=6), nullable=True, comment='Порог входа (уровень отклонения базиса)'))
    op.add_column('portfolio_configs', sa.Column('leaves_qty', sa.Integer(), nullable=True, comment='Остаток объёма для исполнения (leaves_qty)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_configs', 'leaves_qty')
    op.drop_column('portfolio_configs', 'threshold')
    op.drop_column('portfolio_configs', 'price_ratio')
    op.drop_column('portfolio_configs', 'qty_ratio')
    op.drop_column('portfolio_configs', 'mode')
    op.drop_column('portfolio_configs', 'strategy_id')
    # ### end Alembic commands ###
