"""remove_md_dt_columns

Revision ID: 3307220fb297
Revises: f0313720b381
Create Date: 2025-08-26 17:01:44.826980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3307220fb297'
down_revision: Union[str, None] = 'f0313720b381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairs_table', 'md_dt_2')
    op.drop_column('pairs_table', 'md_dt_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairs_table', sa.Column('md_dt_1', sa.DATETIME(), nullable=True))
    op.add_column('pairs_table', sa.Column('md_dt_2', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
