"""clean_initial_migration_from_commit_0843241

Revision ID: 394193e71383
Revises: 
Create Date: 2025-08-26 18:12:01.036542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '394193e71383'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=True),
    sa.Column('broker', sa.String(length=64), nullable=True),
    sa.Column('account_number', sa.String(length=32), nullable=True),
    sa.Column('client_code', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('class_code', sa.String(length=16), nullable=True),
    sa.Column('sec_code', sa.String(length=32), nullable=True),
    sa.Column('price_step', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('board', sa.String(length=16), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('pairs_columns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pairs_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_1', sa.String(length=32), nullable=True),
    sa.Column('asset_2', sa.String(length=32), nullable=True),
    sa.Column('account_1', sa.String(length=64), nullable=True),
    sa.Column('account_2', sa.String(length=64), nullable=True),
    sa.Column('side_1', sa.String(length=4), nullable=True),
    sa.Column('side_2', sa.String(length=4), nullable=True),
    sa.Column('qty_ratio_1', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('qty_ratio_2', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price_ratio_1', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price_ratio_2', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('target_qty', sa.Integer(), nullable=True),
    sa.Column('exec_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exec_qty', sa.Integer(), nullable=True),
    sa.Column('leaves_qty', sa.Integer(), nullable=True),
    sa.Column('strategy_name', sa.String(length=64), nullable=True),
    sa.Column('price_1', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price_2', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('hit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('get_mdata', sa.Boolean(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('md_dt_1', sa.DateTime(), nullable=True),
    sa.Column('md_dt_2', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('qty_ratio', sa.String(length=64), nullable=True),
    sa.Column('price_ratio', sa.String(length=64), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('leaves_qty', sa.Integer(), nullable=True),
    sa.Column('config_json', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pid', name='uq_portfolio_pid')
    )
    op.create_index('ix_portfolio_active', 'portfolio_configs', ['active'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quik_num', sa.Integer(), nullable=True),
    sa.Column('trans_id', sa.Integer(), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='side'), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('filled', sa.Integer(), nullable=False),
    sa.Column('leaves_qty', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACTIVE', 'PARTIAL', 'FILLED', 'CANCELLED', 'REJECTED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_portfolio_status', 'orders', ['portfolio_id', 'status'], unique=False)
    op.create_index('ix_orders_trans_id', 'orders', ['trans_id'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='side'), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'instrument_id', name='uq_position_portfolio_instrument')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('bid_qty', sa.Integer(), nullable=False),
    sa.Column('ask', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('ask_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_inst_ts', 'quotes', ['instrument_id', 'ts'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_inst_ts', 'trades', ['instrument_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_inst_ts', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_quotes_inst_ts', table_name='quotes')
    op.drop_table('quotes')
    op.drop_table('portfolio_positions')
    op.drop_index('ix_orders_trans_id', table_name='orders')
    op.drop_index('ix_orders_portfolio_status', table_name='orders')
    op.drop_table('orders')
    op.drop_table('settings')
    op.drop_index('ix_portfolio_active', table_name='portfolio_configs')
    op.drop_table('portfolio_configs')
    op.drop_table('pairs_table')
    op.drop_table('pairs_columns')
    op.drop_table('instruments')
    op.drop_table('assets_table')
    op.drop_table('accounts_table')
    # ### end Alembic commands ###
