"""add trans_id to order

Revision ID: c5b795ab666c
Revises: ca4d4ec8b034
Create Date: 2025-05-06 09:29:04.215930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b795ab666c'
down_revision: Union[str, None] = 'ca4d4ec8b034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('trans_id', sa.Integer(), nullable=True, comment='ID транзакции QUIK (TRANS_ID)'))
    op.create_index('ix_orders_trans_id', 'orders', ['trans_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_trans_id', table_name='orders')
    op.drop_column('orders', 'trans_id')
    # ### end Alembic commands ###
