"""order: добавлены leaves_qty и strategy_id

Revision ID: ca4d4ec8b034
Revises: 0c2271c73cb4
Create Date: 2025-05-05 18:19:59.290155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4d4ec8b034'
down_revision: Union[str, None] = '0c2271c73cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('strategy_id', sa.Integer(), nullable=True, comment='ID стратегии (если нужно)'))
    op.add_column('orders', sa.Column('leaves_qty', sa.Integer(), nullable=True, comment='Остаток объёма для исполнения (leaves_qty)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'leaves_qty')
    op.drop_column('orders', 'strategy_id')
    # ### end Alembic commands ###
